### ISSUE TITLE
No option to clone a repository 

### ISSUE THREAD

**Issue by ghost** [Chaos-19/Acode-Clone-repository#1]
1. Install ACode (Android 13, paid version from the Google play store)
2. Install this plugin
3. Open a folder, look in all of the available menus and fail to find an option to clone a repository.

What am I missing? 

![Screenshot_2023-11-30-13-52-37-672](https://github.com/Chaos-19/Acode-Clone-repository/assets/135083158/fb07f49b-c68a-4dbc-9179-54cceaa98e54)

![Screenshot_2023-11-30-13-47-55-329](https://github.com/Chaos-19/Acode-Clone-repository/assets/135083158/fe79dc1e-6cb6-4ec4-a1b8-95ee0fbb9ae5)

![Screenshot_2023-11-30-13-51-22-428](https://github.com/Chaos-19/Acode-Clone-repository/assets/135083158/e2f59e18-9655-4d27-bef5-61486807e146)

**Comment by Chaos-19** [comment]
It in command palette check it there 
Click ctrl shift p and search for clone repository

**Comment by ghost** [comment]
Thanks.
