### ISSUE TITLE
Error when cloning from gitlab

### ISSUE THREAD

**Issue by Destro9000** [Chaos-19/Acode-Clone-repository#2]
Hello i keep getting this error after the repo is cloned and im trying to save it somewhere 

"NotFoundError: could not find main"

The repo is this one 
https://gitlab.com/shosetsuorg/extensions.git

**Comment by Chaos-19** [comment]
An unexpected behavior in the code's ref selection resulted in the default cloning of the main branch. To address this issue and provide greater user control, I implemented a modification allowing the selection of any desired branch. Just update the plugin

**Comment by Destro9000** [comment]
I will try thanks
