### ISSUE TITLE
Error Cloning

### ISSUE THREAD

**Issue by AdrielXXO** [Chaos-19/Acode-Clone-repository#3]
I can't clone a repo. 😔 

https://github.com/Chaos-19/Acode-Clone-repository/assets/74346704/d6b43310-9def-4185-a711-2297e572726e

**Comment by Chaos-19** [comment]
The URL you entered is not a valid GitHub repository HTTPS URL. Please ensure that the GitHub URL you entered is valid. 
`e.g
https://github.com/Chaos-19/Acode-Clone-repository.git` 
like this

**Comment by Adrielk00** [comment]
I tried again. And i cant. Now appears others messages.

Cargando Screen_Recording_20240421-160155_Acode.mp4 …
