### ISSUE TITLE
Capabilities and Limitations

### ISSUE THREAD

**Issue by RichNSD** [Chaos-19/Acode-Clone-repository#5]
## Summary

Can you clarify *exactly* what this extension can *and can't* do? Specifically in regards to Git functionality. Does it just download repositories and nothing else?

## Specific Questions

1. After cloning a repository, can this extension push updates/commits to the online Git repositories?
2. Do cloned repositories come with the hidden `.git` directory containing the config files used to manually update the repo from a CLI (like Termux)?
3. Is it possible to check for updates in a cloned repository?
4. If the extension doesn't have these features, do you plan on adding them at any point?

**Comment by Chaos-19** [comment]
Hi there,

I apologize for the delay in getting back to you. Thanks for reaching out to clarify the Git functionality of the extension. Currently, the extension focuses on simplifying the initial step of downloading repositories. Here's what it can and can't do:

- **Can**: Clone repositories and save the files in your desired directory.

- **Can't**:
  - Push updates/commits to online Git repositories.
  - Access the hidden `.git` directory containing configuration files for manual updates via CLI.
  - Check for updates within a cloned repository (yet).

While the extension doesn't offer full Git features yet, my original intention was to support them within Acode. Unfortunately, I haven't been able to implement them at this time.

Here's the exciting part: **This is where your input comes in!** I'd love to hear your thoughts on how we could potentially collaborate on adding these functionalities. Do you have any ideas or suggestions?

Even if you don't have specific ideas, any feedback you can provide is valuable.

Thanks again for reaching out, and hopefully we can work together to make this extension even more powerful!

**Comment by RichNSD** [comment]
Sure, I'll help as much as I can, in the meantime you should add these clarifications to the README.

If you want to reach out via chat, I recommend Discord. My username is `rich.nsd`.
