### ISSUE TITLE
Unavailable 

### ISSUE THREAD

**Issue by afash7** [Chaos-19/Acode-Clone-repository#6]
After installation on ACode the plugin is unavailable in file menu

![Screenshot_2024-08-21-01-52-20-451_com.foxdebug.acode-edit.jpg](https://github.com/user-attachments/assets/b436b0fb-3f36-4ef9-b4c0-73362721c9be)

**Comment by Chaos-19** [comment]
It in command palette check it there
Click ctrl shift p and search for clone repository

**Comment by afash7** [comment]
thanks i found it
